ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paymentRef" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paymentProof" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
